### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by jpetso** [xpol/xchange#4]
Your project looks super useful, but it doesn't specify a license so I can't use it in my own project. That makes it less useful.

It would be great if you could choose a license (hopefully open source - maybe Apache License 2.0, Boost License or MIT) and add it as a file LICENSE in the top-level directory. A license header in each file will also help retaining the license if people decide to copy just individual files.

**Comment by jpetso** [comment]
Wow, that was fast! Thanks! :)

**Comment by xpol** [comment]
@jpetso You are welcome!

Thank you for reporting!
