### ISSUE TITLE
Boost license

### ISSUE THREAD

**Issue by jpetso** [xpol/xchange#5]
Hi, as you might be aware, msgpack-c recently switched from Apache to Boost license. I took your code as a starting point for what is now https://github.com/tplgy/json-msgpack/blob/master/include/json_msgpack/json_msgpack_sax.hpp and although it's now very different than your file at https://github.com/xpol/xchange/blob/master/src/msgpack/type/rapidjson/document.hpp, I can't be sure that our copyright has replaced all of yours.

I was hoping to use this converter in https://github.com/crossbario/autobahn-cpp but they've also switched to Boost following the msgpack switch, so they won't like Apache licensing being reintroduced there. (See https://github.com/msgpack/msgpack-c/issues/377 and linked issues for the reasoning on the msgpack-c side.)

I was wondering if you might want to switch to Boost as well, or grant me/us permission to change the license in https://github.com/tplgy/json-msgpack/blob/master/include/json_msgpack/json_msgpack_sax.hpp in case your copyright still applies. (If not then we'll either have to avoid using that project in autobahn-cpp or inspect the code more carefully to see how much, if any, of your copyright still applies to that file.)

Thanks, and I hope it's not too much trouble!

**Comment by xpol** [comment]
May be I can add due Licence.

**Comment by jpetso** [comment]
:)
